/**
 * E2E test: Stdio Proxy path.
 *
 * Spawns the bolyra-proxy (from mcp-demo) with our server as upstream,
 * sends JSON-RPC messages simulating Claude Desktop, and verifies:
 *   1. initialize succeeds
 *   2. tools/list returns expected tools
 *   3. tools/call for read_file works (proof is generated by proxy)
 *   4. Proxy stderr shows proof generation logs
 */

import { spawn, ChildProcess } from 'child_process';
import * as path from 'path';
import * as assert from 'assert';
import * as fs from 'fs';
import * as os from 'os';

// __dirname at runtime is dist/test/ -- navigate up to examples/ for sibling packages
const EXAMPLES_DIR = path.resolve(__dirname, '../../..');
const PROXY_SCRIPT = path.resolve(EXAMPLES_DIR, 'mcp-demo/dist/bolyra-proxy.js');
// Our server is compiled to dist/src/server.js relative to the example root
const EXAMPLE_ROOT = path.resolve(__dirname, '..');
const SERVER_SCRIPT = path.resolve(EXAMPLE_ROOT, 'src/server.js');

// Timeout for the entire test
const TEST_TIMEOUT_MS = 60_000;

interface JsonRpcResponse {
  jsonrpc: '2.0';
  id: string | number | null;
  result?: unknown;
  error?: { code: number; message: string };
}

/**
 * Send a JSON-RPC message to a child process via stdin and wait for a response.
 */
function sendJsonRpc(
  child: ChildProcess,
  method: string,
  params: Record<string, unknown> = {},
  id: number = 1,
): Promise<JsonRpcResponse> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(
      () => reject(new Error(`Timeout waiting for response to ${method} (id=${id})`)),
      30_000,
    );

    let buf = '';
    const onData = (chunk: string) => {
      buf += chunk;
      let nl: number;
      while ((nl = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        if (!line.trim()) continue;
        try {
          const resp = JSON.parse(line) as JsonRpcResponse;
          if (resp.id === id) {
            clearTimeout(timer);
            child.stdout!.removeListener('data', onData);
            resolve(resp);
            return;
          }
        } catch {
          // Not valid JSON, skip
        }
      }
    };

    child.stdout!.setEncoding('utf8');
    child.stdout!.on('data', onData);

    const msg = JSON.stringify({ jsonrpc: '2.0', id, method, params });
    child.stdin!.write(msg + '\n');
  });
}

async function testProxy(): Promise<void> {
  console.log('=== Stdio Proxy E2E Test ===\n');

  // Verify proxy script exists
  if (!fs.existsSync(PROXY_SCRIPT)) {
    console.error(`ERROR: Proxy script not found at ${PROXY_SCRIPT}`);
    console.error('Run: cd examples/mcp-demo && npm install && npm run build');
    process.exit(1);
  }

  // Create a temp file to read
  const tmpFile = path.join(os.tmpdir(), `bolyra-test-${Date.now()}.txt`);
  fs.writeFileSync(tmpFile, 'Hello from Bolyra E2E test!', 'utf8');

  let proxy: ChildProcess | null = null;
  let stderrOutput = '';

  try {
    // Spawn the proxy with our server as upstream
    console.log('Starting bolyra-proxy with upstream server...');
    proxy = spawn('node', [PROXY_SCRIPT], {
      env: {
        ...process.env,
        BOLYRA_UPSTREAM_SCRIPT: SERVER_SCRIPT,
        // Ensure BOLYRA_TRANSPORT is set to stdio for the upstream server
        BOLYRA_TRANSPORT: 'stdio',
      },
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    proxy.stderr!.setEncoding('utf8');
    proxy.stderr!.on('data', (chunk: string) => {
      stderrOutput += chunk;
      process.stderr.write(`  [proxy-stderr] ${chunk}`);
    });

    proxy.on('error', (err) => {
      console.error('Proxy spawn error:', err);
    });

    // Wait for proxy to initialize (it loads demo identities)
    console.log('Waiting for proxy to load identities...');
    await waitForStderr(proxy, 'spawning upstream', 30_000);
    // Give the upstream a moment to start
    await sleep(2000);

    // Test 1: Initialize
    console.log('\n[Test 1] Sending initialize...');
    const initResp = await sendJsonRpc(
      proxy,
      'initialize',
      {
        protocolVersion: '2024-11-05',
        capabilities: {},
        clientInfo: { name: 'test-client', version: '0.1.0' },
      },
      1,
    );
    assert.strictEqual(initResp.jsonrpc, '2.0');
    assert.ok(initResp.result, 'initialize should return a result');
    const initResult = initResp.result as Record<string, unknown>;
    assert.ok(initResult.serverInfo, 'should have serverInfo');
    console.log('  PASS: initialize returned serverInfo');

    // Send initialized notification
    proxy.stdin!.write(
      JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized', params: {} }) + '\n',
    );
    await sleep(500);

    // Test 2: tools/list
    console.log('\n[Test 2] Sending tools/list...');
    const listResp = await sendJsonRpc(proxy, 'tools/list', {}, 2);
    assert.ok(listResp.result, 'tools/list should return a result');
    const listResult = listResp.result as { tools: Array<{ name: string }> };
    assert.ok(Array.isArray(listResult.tools), 'should have tools array');
    const toolNames = listResult.tools.map((t) => t.name);
    assert.ok(toolNames.includes('read_file'), 'should include read_file tool');
    console.log(`  PASS: tools/list returned ${listResult.tools.length} tools: [${toolNames.join(', ')}]`);

    // Test 3: tools/call (read_file)
    console.log('\n[Test 3] Sending tools/call for read_file...');
    const callResp = await sendJsonRpc(
      proxy,
      'tools/call',
      { name: 'read_file', arguments: { path: tmpFile } },
      3,
    );

    if (callResp.error) {
      // Proof generation failure is acceptable in CI (no rapidsnark binary)
      // but we should still see the attempt in stderr
      console.log(`  INFO: tools/call returned error: ${callResp.error.message}`);
      if (callResp.error.message.includes('Bolyra proof generation failed')) {
        console.log('  PASS (expected): Proof generation failed (likely no circuit artifacts)');
        console.log('  The proxy correctly attempted to generate a proof before forwarding.');
      } else {
        throw new Error(`Unexpected error: ${callResp.error.message}`);
      }
    } else {
      assert.ok(callResp.result, 'tools/call should return a result');
      const callResult = callResp.result as { content: Array<{ type: string; text: string }> };
      assert.ok(callResult.content, 'should have content');
      assert.strictEqual(callResult.content[0]?.text, 'Hello from Bolyra E2E test!');
      console.log('  PASS: read_file returned correct content');
    }

    // Test 4: Verify proxy stderr shows proof activity
    console.log('\n[Test 4] Checking proxy stderr for proof activity...');
    assert.ok(
      stderrOutput.includes('[bolyra-proxy]'),
      'stderr should contain proxy log messages',
    );
    assert.ok(
      stderrOutput.includes('loading demo identities'),
      'stderr should show identity loading',
    );
    console.log('  PASS: Proxy logs show expected activity');

    console.log('\n=== All Stdio Proxy Tests Passed ===\n');
  } finally {
    // Cleanup
    if (proxy && !proxy.killed) {
      proxy.stdin!.end();
      proxy.kill('SIGTERM');
      await sleep(500);
      if (!proxy.killed) proxy.kill('SIGKILL');
    }
    try {
      fs.unlinkSync(tmpFile);
    } catch {
      // ignore
    }
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function waitForStderr(child: ChildProcess, substring: string, timeoutMs: number): Promise<void> {
  return new Promise((resolve, reject) => {
    let buf = '';
    const timer = setTimeout(
      () => reject(new Error(`Timeout waiting for stderr to contain "${substring}"`)),
      timeoutMs,
    );

    const onData = (chunk: string) => {
      buf += chunk;
      if (buf.includes(substring)) {
        clearTimeout(timer);
        child.stderr!.removeListener('data', onData);
        resolve();
      }
    };

    child.stderr!.setEncoding('utf8');
    child.stderr!.on('data', onData);

    // Check if already received
    if (buf.includes(substring)) {
      clearTimeout(timer);
      child.stderr!.removeListener('data', onData);
      resolve();
    }
  });
}

// Run with timeout
const timeout = setTimeout(() => {
  console.error('ERROR: Test timed out');
  process.exit(1);
}, TEST_TIMEOUT_MS);

testProxy()
  .then(() => {
    clearTimeout(timeout);
    process.exit(0);
  })
  .catch((err) => {
    clearTimeout(timeout);
    console.error('\nTEST FAILED:', err);
    process.exit(1);
  });
