// timeline_how.jsx — the "How Bolyra works" timeline (58 s). Shared by the dev page
// (Bolyra How It Works.html) and the production page (landing/video-how-it-works.html,
// generated by inline-how.mjs).

const HOW_DURATION = 58;

function HowTimecodeTag() {
  const time = useTime();
  React.useEffect(() => {
    const el = document.getElementById('video-root');
    if (el) el.setAttribute('data-screen-label', 't=' + time.toFixed(0) + 's');
  }, [Math.floor(time)]);
  return null;
}

function HowCap(props) {
  return (
    <Sprite start={props.start} end={props.end}>
      {({ localTime }) => (
        <Caption t={localTime} dur={props.end - props.start} y={104}
          kicker={props.kicker} title={props.title} sub={props.sub} />
      )}
    </Sprite>
  );
}

function HowVideo() {
  return (
    <Stage width={1920} height={1080} duration={HOW_DURATION} background="#0a0c10" persistKey="bolyra-how">
      <Backdrop glowX={960} glowY={540} />
      <HowTimecodeTag />

      {/* S0 Title 0–5 */}
      <Sprite start={0} end={5.2}>{({ localTime }) => <TitleScene t={localTime} dur={5.2} />}</Sprite>

      {/* S1 Mandate 5–16 */}
      <Sprite start={5} end={16.2}>{({ localTime }) => <MandateScene t={localTime} dur={11.2} />}</Sprite>
      <HowCap start={5.6} end={15.8} kicker="1 · The mandate" title="One operator signature binds agent, audience, capability and expiry." sub="Altering the signed binding fails verification." />

      {/* honesty label from the first simulated output to the end */}
      <Sprite start={5.4} end={HOW_DURATION}>{({ localTime }) => <HonestyLabel appear={clamp(localTime / 0.6, 0, 1)} />}</Sprite>

      {/* S2 Verdict 16–36 */}
      <Sprite start={16} end={36.2}>{({ localTime }) => <VerdictScene t={localTime} dur={20.2} />}</Sprite>
      <HowCap start={16.6} end={35.8} kicker="2 · The verdict" title="Checked before any payment logic runs." sub="Over-scope and missing mandates fail closed. RFC 9457 problem details." />

      {/* S3 Receipts 36–46 */}
      <Sprite start={36} end={46.2}>{({ localTime }) => <ReceiptChainScene t={localTime} dur={10.2} />}</Sprite>
      <HowCap start={36.6} end={45.8} kicker="3 · The receipt" title="Every decision this gate makes, allow and deny, on one hash chain." sub="Verified with the public key; a known count detects a shortened chain." />

      {/* S4 Boundary 46–53 */}
      <Sprite start={46} end={53.2}>{({ localTime }) => <BoundaryScene t={localTime} dur={7.2} />}</Sprite>
      <HowCap start={46.6} end={52.8} kicker="Where it applies" title="Only where the relying party verifies." />

      {/* S5 CTA 53–58 */}
      <Sprite start={53} end={HOW_DURATION}>{({ localTime }) => <HowCTA t={localTime} dur={HOW_DURATION - 53} />}</Sprite>
    </Stage>
  );
}

ReactDOM.createRoot(document.getElementById('video-root')).render(<HowVideo />);
