// Writes integrations/hosted-verify/.dev.vars for a local or CI run of this example:
// the repo's documented placeholder tenant (the TENANTS line of .dev.vars.example,
// verbatim), the mpp capability vocabulary taken from the INSTALLED @bolyra/mpp (never
// hand-typed), and a throwaway receipt signing key so the Worker emits receipts.
// Prints byte counts only — never the file's contents.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const { MPP_CAPABILITY_MAP } = require('@bolyra/mpp');

const here = path.dirname(fileURLToPath(import.meta.url));
const hostedVerify = path.resolve(here, '..', '..', '..', 'integrations', 'hosted-verify');
const example = readFileSync(path.join(hostedVerify, '.dev.vars.example'), 'utf8');
const tenants = example.split('\n').find((line) => line.startsWith('TENANTS='));
if (tenants === undefined) throw new Error('.dev.vars.example has no TENANTS line');

// Deterministic test-only signing key (the one the Worker's own suite uses). NOT a secret.
const RECEIPT_SIGNER_KEY = '0x0101010101010101010101010101010101010101010101010101010101010101';

const out = [
  '# Generated by examples/managed-revocation/scripts/dev-vars.mjs — placeholders, not secrets.',
  tenants,
  `CAPABILITY_MAP=${JSON.stringify(MPP_CAPABILITY_MAP)}`,
  `RECEIPT_SIGNER_KEY=${RECEIPT_SIGNER_KEY}`,
  '',
].join('\n');
const target = path.join(hostedVerify, '.dev.vars');
writeFileSync(target, out, { mode: 0o600 });
console.log(`wrote ${path.relative(process.cwd(), target)} (${Buffer.byteLength(out)} bytes)`);
