// Writes integrations/hosted-verify/.dev.vars for a local or CI run of this example:
// the repo's documented placeholder tenant (the TENANTS line of .dev.vars.example,
// verbatim), the mpp capability vocabulary taken from the INSTALLED @bolyra/mpp (never
// hand-typed), and a throwaway receipt signing key so the Worker emits receipts.
// Refuses to overwrite a .dev.vars it did not write. Prints byte counts only — never
// the file's contents.
import { chmodSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const { MPP_CAPABILITY_MAP } = require('@bolyra/mpp');
if (MPP_CAPABILITY_MAP === null || typeof MPP_CAPABILITY_MAP !== 'object') {
  throw new Error('@bolyra/mpp does not export MPP_CAPABILITY_MAP — check the pinned version');
}

const here = path.dirname(fileURLToPath(import.meta.url));
const hostedVerify = path.resolve(here, '..', '..', '..', 'integrations', 'hosted-verify');
const example = readFileSync(path.join(hostedVerify, '.dev.vars.example'), 'utf8');
const tenantLines = example.split(/\r?\n/).filter((line) => line.startsWith('TENANTS='));
if (tenantLines.length !== 1) {
  throw new Error(`.dev.vars.example must have exactly one TENANTS line; found ${tenantLines.length}`);
}
const tenants = tenantLines[0];

// Deterministic test-only signing key — the one integrations/hosted-verify/vitest.config.mts
// gives the Worker's own suite. NOT a secret.
const RECEIPT_SIGNER_KEY = '0x0101010101010101010101010101010101010101010101010101010101010101';

const HEADER = '# Generated by examples/managed-revocation/scripts/dev-vars.mjs — placeholders, not secrets.';
const out = [
  HEADER,
  tenants,
  `CAPABILITY_MAP=${JSON.stringify(MPP_CAPABILITY_MAP)}`,
  `RECEIPT_SIGNER_KEY=${RECEIPT_SIGNER_KEY}`,
  '',
].join('\n');
const target = path.join(hostedVerify, '.dev.vars');
if (existsSync(target) && !readFileSync(target, 'utf8').startsWith(HEADER)) {
  throw new Error(`${target} exists and was not written by this script; move it aside first`);
}
writeFileSync(target, out, { mode: 0o600 });
chmodSync(target, 0o600); // `mode` applies only when the file is created
console.log(`wrote ${path.relative(process.cwd(), target)} (${Buffer.byteLength(out)} bytes)`);
